from fastapi import APIRouter
from pydantic import BaseModel
from rl_engine.policy import rl_agent
from llm_engine.claude_service import claude_service

router = APIRouter(prefix="/ai", tags=["AI & Automation"])

class StateRequest(BaseModel):
    temperature_c: float
    co2_ppm: float
    estimated_count: int

@router.post("/action")
async def get_recommended_action(state: StateRequest):
    """
    Given an environmental state, returns the RL agent's recommended HVAC action
    and a natural language explanation generated by Claude.
    """
    state_dict = state.model_dump()
    action = rl_agent.get_action(state_dict, inference_only=True)
    explanation = await claude_service.generate_explanation(state_dict)
    
    action_map = {0: "OFF", 1: "LOW", 2: "MEDIUM", 3: "HIGH"}
    
    return {
        "recommended_action": action,
        "action_name": action_map.get(action, "UNKNOWN"),
        "explanation": explanation
    }
